# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
env_files:
  github_token: ~/.config/goreleaser/github_token
before:
  hooks:
    - go mod tidy
    - go mod vendor
    - go generate ./...
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
  flags:
    - -mod=vendor
  ldflags:
    - -w -s -X main.version={{.Version}} -X main.build={{ time "2006-01-02T15:04:05" }}
archives:
- replacements:
    darwin: macos
    linux: linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
